info:
  group: "@project.groupId@"
  artifact: "@project.artifactId@"
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  contact: 정성현 <hashmap27@gmail.com> or <public27@naver.com>
server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false 